Week 4/Day 5/Cloneit/config/routes.rb
Rails.application.routes.draw do
  resources :subs
  resource :user
  resource :session, only: [:create, :new]
  get 'session/logout', to: 'sessions#logout', as: 'logout'
end

Week 4/Day 5/Cloneit/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  belongs_to :parent, class_name: "Comment"

end

Week 4/Day 5/Cloneit/app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  
end

Week 4/Day 5/Cloneit/app/models/session_token.rb
class SessionToken < ActiveRecord::Base
  validates :user, :value, presence: true

  belongs_to :user

  def self.new_token(user)
    token = SessionToken.new(user_id: user.id)
    token.value = SecureRandom.urlsafe_base64
    token
  end

end

Week 4/Day 5/Cloneit/app/models/sub.rb
class Sub < ActiveRecord::Base
end

Week 4/Day 5/Cloneit/app/models/sub_link.rb
class SubLink < ActiveRecord::Base
end

Week 4/Day 5/Cloneit/app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  validates :username, :email, :password_digest, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many :session_tokens, dependent: :destroy
  has_many :comments

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return user unless user #exists
    user.is_password?(password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
end

Week 4/Day 5/Cloneit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :current_token

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= current_token.user
  end

  def current_token
    return nil if session[:session_token].nil?
    @current_token ||= SessionToken.find_by_value(session[:session_token])
  end

  def login(user)
    token = SessionToken.new_token(user)
    token.save!
    session[:session_token] = token.value
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

Week 4/Day 5/Cloneit/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if @user.nil?
      flash.now[:errors] ||= []
      flash.now[:errors]  << "Invalid username or password."
      render :new
    else
      login(@user)
      redirect_to :user
    end
  end

  def new
    if current_user
      redirect_to user_url
    else
      @user = User.new
      render :new
    end
  end

  def logout
    self.current_token.destroy!
    session[:session_token] = nil
    redirect_to new_session_url
  end
end

Week 4/Day 5/Cloneit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :force_login
  before_action :not_the_mod, only: :edit

  def index
    @subs = Sub.all
    render :index
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      render :new
    end
  end

  def edit

  end

  def show
    @sub = Sub.find_by(params[:id])
    render json: @sub
  end

  private

  def force_login
    redirect_to new_session_url if current_user.nil?
  end

  def not_the_mod
    @sub = Sub.new(sub_params)
    unless @sub.moderator == current_user
      current_user[:errors] << "Must be the moderator to edit this session"
    end
  end

  def sub_params
    params.require(:sub).permit(:description, :title)
  end

end

Week 4/Day 5/Cloneit/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    if current_user
      redirect_to user_url
    else
      @user = User.new
      render :new
    end
  end

end

Week 4/Day 5/Cloneit/app/helpers/sessions_helper.rb
module SessionsHelper
end

Week 4/Day 5/Cloneit/app/helpers/subs_helper.rb
module SubsHelper
end

Week 4/Day 5/Cloneit/app/helpers/users_helper.rb
module UsersHelper
end

Week 4/Day 5/Cloneit/app/views/layouts/_login.html.erb
<h1>Create Account</h1>
<form action="<%=user_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <p>
    <label for="username">Username:</label>
    <input type="text"
    name="user[username]"
    value="<%=@user.username%>"
    placeholder="username">
  </p>

  <p>
    <label for="email">Email:</label>
    <input type="text"
    name="user[email]"
    value="<%=@user.email%>"
    placeholder="email">
  </p>

  <p>
    <label for="password">Password:</label>
    <input type="password"
    name="user[password]">
  </p>
  <p><input type="submit"></p>
</form>

Week 4/Day 5/Cloneit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cloneit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <% if current_user %>
    <%= link_to "Sign Out", logout_url %>
  <% else %>
    <%= link_to "Sign In", new_session_url%>
    <%= link_to "Sign Up", new_user_url%>
  <% end %>

  <% flash.now[:errors].try(:each) do |msg| %>
    <p><%= msg %></p>
  <% end %>

  <%= yield %>

</body>

</html>

Week 4/Day 5/Cloneit/app/views/subs/index.html.erb
<h1>All SubCloneits</h1>
<% @subs.each do |sub|%>
  <p>Title: <%= link_to sub.title, sub_url(sub.id) %></p>
  <p>Description: <%= sub.description %></p>
<% end %>

Week 4/Day 5/Cloneit/app/views/subs/new.html.erb
<h1>Create New Sub</h1>

<form action="<%=subs_url%>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%=form_authenticity_token%>">

  <label for="title">Title:</label>
  <input
    type="text"
    name="sub[title]"
    value="<%=@sub.title%>"
    id="title">

  <label for="description">Description:</label>
  <input
    type="text"
    name="sub[description]"
    value="<%=@sub.description%>"
    id="description">

  <input type="submit" value="Submit!">
</form>