Week 4/Day 4/MusicApp/config/routes.rb
Rails.application.routes.draw do
  post 'session', to: 'sessions#create'
  get 'new_sessions', to: 'sessions#new'
  post 'session/logout', to: 'sessions#logout', as: 'logout_session'
  post 'users', to: 'users#create'
  get 'new_user', to: 'users#new'
  get 'user', to: 'users#show'

  resources :bands

  get '/band/:band_id/albums/new', to: 'albums#new', as: 'new_band_album'
  resources :albums

  get '/albums/:abum_id/tracks/new', to: 'tracks#new', as: 'new_album_track'
  resources :tracks
end

Week 4/Day 4/MusicApp/app/models/album.rb
class Album < ActiveRecord::Base
  STYLES = ["LIVE", "STUDIO"]
  has_many :tracks, dependent: :destroy
  belongs_to :band
  validates :title, :band_id, :style, presence: true
  validate :is_valid_style

  def is_valid_style
    unless STYLES.include?(self.style.upcase) && !self.style.empty?
       errors[:style] << "Must be recorded live or in studio."
     end
  end
end

Week 4/Day 4/MusicApp/app/models/band.rb
class Band < ActiveRecord::Base
  has_many :albums, dependent: :destroy
  has_many :tracks, through: :albums

  validates :name, presence: true
end

Week 4/Day 4/MusicApp/app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :album
  validates :name, :album_id, :bonus, presence: true
end

Week 4/Day 4/MusicApp/app/models/user.rb
class User < ActiveRecord::Base
  after_initialize :ensure_has_token
  validates :email, :password_digest, :session_token, presence: true
  validates :email, :session_token, uniqueness: true

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64
  end

  def ensure_has_token
    session_token || reset_token!
  end

  def password=(pass)
    self.password_digest = BCrypt::Password.create(pass)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end
end

Week 4/Day 4/MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
  end

  private
  def album_params
    params.require(:album).permit(:title, :style)
  end
end

Week 4/Day 4/MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  helper_method :current_user
  protect_from_forgery with: :exception

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def log_in!(user)
    session[:session_token] = user.session_token
    redirect_to user_url
  end
end

Week 4/Day 4/MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def delete
    #deletes band
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    band = Band.new(params[:band][:name])
    if band.save
      redirect_to bands_url
    else
      flash[:errors] << band.errors.full_messages
      render :new
    end
  end
end

Week 4/Day 4/MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    user = User.new
  end

  def logout
    current_user.reset_token!
    session[:session_token] = nil
    redirect_to new_user_url
  end


  def create
    user = User.find_by_credentials(
                                    params[:user][:email],
                                    params[:user][:password]
                                    )
    if user
      log_in!(user)
    else
      flash[:errors] = "Incorrect Username/Password"
      render :new
    end
  end
end

Week 4/Day 4/MusicApp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
end

Week 4/Day 4/MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      log_in!(user)
    else
      flash[:errors] = user.errors.full_messages
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

Week 4/Day 4/MusicApp/app/helpers/album_helper.rb
module AlbumHelper
end

Week 4/Day 4/MusicApp/app/helpers/band_helper.rb
module BandHelper
end

Week 4/Day 4/MusicApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

Week 4/Day 4/MusicApp/app/helpers/track_helper.rb
module TrackHelper
end

Week 4/Day 4/MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

Week 4/Day 4/MusicApp/app/views/bands/index.html.erb
<% @bands.each do |band| %>
  <p><%= link_to "#{band.name} Albums", band_url(band.id)%></p>
<% end %>
<%= link_to "Create Band", new_band_url %>

Week 4/Day 4/MusicApp/app/views/bands/new.html.erb
<form action="<%= bands_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <h1>Create a new Band!</h1>
  <label for="band_name">Band Name</label>
  <input type="text" name="band[name]" placeholder="Band Name Here" id="band_name">
  <input type="submit" value="Make This Band!">
</form>

Week 4/Day 4/MusicApp/app/views/bands/show.html.erb
<h1> <%= @band.name %> </h1>
<ul>
  <% @band.albums.each do |album| %>
    <li> <%= album.name %> (<%= album.syle %>) </li>
  <% end %>
</ul>
<%= link_to "Create Album", new_band_album_url(@band) %>

Week 4/Day 4/MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%=flash[:errors] if flash[:errors]%>
  <% if content_for? :header %>
    <%= :header %>
  <% else %>
    <title>MusicApp</title>
  <% end %>
  <%if current_user%>
    <%= button_to "Logout", logout_session_url%>
  <%else%>
    <%= link_to "Sign In", new_sessions_url%>
  <% end %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>